version: '3.6'

services:
  web:
    build: .
    command: gunicorn --reload --bind 0.0.0.0 blog.wsgi
    env_file:
      - .env
    ports:
      - 80:8000
    tty: true
    volumes:
      - ./:/code
    working_dir: /code
